console.log("Operators in JS")
console.log("")
console.log("Arithmetic Operators :")
console.log("+ - * ** / % ++ --")
console.log("")
console.log("Assignment Operators")
console.log("= += -= *= **= /= %= ")
console.log("")
console.log("Comparison Operators")
console.log("== != === !== > < >= <= ?")
console.log("")
console.log("Logical Operators")
console.log("&& || !")
console.log("")
console.log("Bitwise Operators")
console.log("& | ^ ! << >> >>> <<<")

let a = 20
let b = 5
console.log("")
console.log("quiz")

console.log("")
console.log("a++ : ", ++a)
console.log("a++ : ", a++)
console.log("--a : ", --a)
console.log("a-- : ", a--)
console.log("a : ", a)
console.log("a-- : ", a--)
